# Generated by Django 4.2.3 on 2023-09-13 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("petapp", "0002_rename_uname_log_email_user_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="log",
            name="role",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name="seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=30, null=True)),
                ("name", models.CharField(max_length=30, null=True)),
                ("phone", models.CharField(max_length=30, null=True)),
                ("shop", models.CharField(max_length=30, null=True)),
                ("pin", models.CharField(max_length=30, null=True)),
                ("adress", models.CharField(max_length=150, null=True)),
                (
                    "login",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petapp.log"
                    ),
                ),
            ],
        ),
    ]
