# Generated by Django 3.2.18 on 2023-09-20 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_pet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='desciptiion',
            new_name='descriptiion',
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.FileField(max_length=30, null=True, upload_to=''),
        ),
    ]
