# Generated by Django 4.2.3 on 2023-09-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petapp", "0009_rename_descriptiion_pet_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
