# Generated by Django 4.2.3 on 2023-10-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petapp", "0012_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="adress",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
