# Generated by Django 4.2.3 on 2023-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petapp", "0014_remove_pet_adress_booking_adress"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="petname",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="quantity",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
