# Generated by Django 4.2.3 on 2023-10-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petapp", "0015_payment_petname_payment_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="breed",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
